
amcl:
  ros__parameters:
    use_sim_time: true
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    laser_model_type: likelihood_field
    laser_likelihood_max_dist: 2.0
    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    tf_broadcast: true
    laser_max_range: 3.5 # Max range of simulated LIDAR
