
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: true
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.15 # Adjusted for robot base size
      plugins:
        - {name: obstacle_layer,         type: "nav2_costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,        type: "nav2_costmap_2d::InflationLayer"}
      obstacle_layer:
        enabled: true
        obstacle_range: 2.5
        raytrace_range: 3.0
        max_obstacle_height: 2.0
        topics: ["scan"]
      inflation_layer:
        enabled: true
        cost_scaling_factor: 3.0
        inflation_radius: 0.5
